- name: Enable Corepack
  run: corepack enable

- name: Setup Node.js environment
  uses: actions/setup-node@v6.5.0
  with:
    node-version: '20' # Or your desired version
    cache: 'yarn' # Automatically detects and hashes your yarn.lock file

- name: Install dependencies
  run: yarn install --immutable # The standard flags for CI on Yarn Modern
